version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16

  pre_build:
    commands:
      - echo "check prebuild"
      # - npm test

  build:
    commands:
      - echo "Build phase complete. No specific build command for this Node.js app."
      - echo "Installing dependencies..."
      - npm install --production

  post_build:
    commands:
      - echo "Running test"

artifacts:
  files:
    - '**/*' 
  base-directory: . 
